name: ReactJS CI CD
on: workflow_dispatch
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
            - name: Test the code
              run: npm test